# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       dbus

# >> macros
%define dbus_user_uid 81
# << macros

Summary:    D-Bus message bus
Version:    1.8.6
Release:    1
Group:      System/Libraries
License:    GPLv2+ or AFL
URL:        http://www.freedesktop.org/software/dbus/
Source0:    %{name}-%{version}.tar.xz
Source1:    dbus-user.socket
Source2:    dbus-user.service
Source100:  dbus.yaml
Patch0:     ensure-machine-id-in-start.patch
Requires:   %{name}-libs = %{version}
Requires:   systemd
Requires(pre): /usr/sbin/useradd
Requires(preun): systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(expat) >= 1.95.5
BuildRequires:  gettext
BuildRequires:  libcap-devel
BuildRequires:  libtool
BuildRequires:  xmlto
BuildRequires:  systemd-libs

%description
D-Bus is a system for sending messages between applications. It is used both
for the systemwide message bus service, and as a per-user-login-session
messaging facility.


%package libs
Summary:    Libraries for accessing D-Bus
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
Lowlevel libraries for accessing D-Bus.

%package devel
Summary:    Libraries and headers for D-Bus
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   pkgconfig

%description devel
Headers and static libraries for D-Bus.

%package x11
Summary:    X11-requiring add-ons for D-Bus
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description x11
D-Bus contains some tools that require Xlib to be installed, those are in this
separate package so server systems need not install X.


%prep
%setup -q -n %{name}-%{version}/upstream

# ensure-machine-id-in-start.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre

# Start dbus earlier
sed -i 's,multi-user.target.wants,basic.target.wants,g' bus/Makefile.am

# << build pre

%reconfigure --disable-static \
    --exec-prefix=/ \
    --bindir=/bin \
    --libexecdir=%{_libdir}/dbus-1 \
    --sysconfdir=%{_sysconfdir} \
    --disable-tests \
    --disable-asserts \
    --disable-xml-docs \
    --disable-doxygen-docs \
    --disable-selinux \
    --disable-libaudit \
    --disable-dnotify \
    --with-system-pid-file=/run/dbus/pid \
    --with-system-socket=/run/dbus/system_bus_socket \
    --with-console-auth-dir=/run/console/ \
    --with-dbus-user=dbus \
    --with-systemdsystemunitdir="%{_unitdir}" \
    --enable-systemd \
    --enable-inotify

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p %{buildroot}%{_datadir}/dbus-1/interfaces

mkdir -p %{buildroot}%{_userunitdir}
install -m0644 %{SOURCE1} %{buildroot}%{_userunitdir}/dbus.socket
install -m0644 %{SOURCE2} %{buildroot}%{_userunitdir}/dbus.service

# Move /var/run to /
mv %{buildroot}%{_localstatedir}/run %{buildroot}/run

# Remove documentation
rm -fr %{buildroot}%{_datadir}/doc/dbus/

# << install post

%pre
# >> pre
# Add the "dbus" user and group
[ -e /usr/sbin/groupadd ] && /usr/sbin/groupadd -r -g %{dbus_user_uid} dbus 2>/dev/null || :
[ -e /usr/sbin/useradd ] && /usr/sbin/useradd -c 'System message bus' -u %{dbus_user_uid} \
-g %{dbus_user_uid} -s /sbin/nologin -r -d '/' dbus 2> /dev/null || :
# << pre

%preun
if [ "$1" -eq 0 ]; then
systemctl stop dbus.service
fi

%post
systemctl daemon-reload
systemctl reload-or-try-restart dbus.service

%postun
systemctl daemon-reload

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc COPYING
/bin/dbus-cleanup-sockets
/bin/dbus-daemon
/bin/dbus-monitor
/bin/dbus-send
/bin/dbus-uuidgen
/bin/dbus-run-session
%dir %{_sysconfdir}/dbus-1
%config(noreplace) %{_sysconfdir}/dbus-1/session.conf
%dir %{_sysconfdir}/dbus-1/session.d
%config(noreplace) %{_sysconfdir}/dbus-1/system.conf
%dir %{_sysconfdir}/dbus-1/system.d
%dir /%{_prefix}/%{_lib}/dbus-1
%{_userunitdir}/*
%{_unitdir}/dbus.service
%{_unitdir}/dbus.socket
%{_unitdir}/dbus.target.wants/dbus.socket
%{_unitdir}/basic.target.wants/dbus.service
%{_unitdir}/sockets.target.wants/dbus.socket
%attr(4750,root,dbus) %{_libdir}/dbus-1/dbus-daemon-launch-helper
%dir %{_datadir}/dbus-1
%{_datadir}/dbus-1/interfaces
%{_datadir}/dbus-1/services
%{_datadir}/dbus-1/system-services
%ghost %dir /run/dbus
%dir %{_localstatedir}/lib/dbus
# >> files
# << files

%files libs
%defattr(-,root,root,-)
%{_libdir}/libdbus-1.so.3*
# >> files libs
# << files libs

%files devel
%defattr(-,root,root,-)
%{_libdir}/libdbus-1.so
%{_includedir}/dbus-1.0/dbus/dbus*.h
%dir %{_libdir}/dbus-1.0
%{_libdir}/dbus-1.0/include/dbus/dbus-arch-deps.h
%{_libdir}/pkgconfig/dbus-1.pc
# >> files devel
# << files devel

%files x11
%defattr(-,root,root,-)
%{_bindir}/dbus-launch
# >> files x11
# << files x11
